# Generated by Django 6.0.1 on 2026-02-02 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('power', models.CharField(max_length=150)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(choices=[('KLY', 'KALYAN'), ('MUM', 'MUMBAI'), ('THN', 'THANE'), ('DDR', 'DADAR')], max_length=3)),
            ],
        ),
    ]
