# Generated by Django 6.0.1 on 2026-02-03 04:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hero_work_permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workpermit', to='superhero.superherotype')),
            ],
        ),
        migrations.CreateModel(
            name='heroBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('available_hero', models.ManyToManyField(related_name='hero_branch', to='superhero.superherotype')),
            ],
        ),
        migrations.CreateModel(
            name='HeroReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Avarage'), (4, 'Satisfactory'), (5, 'Good')], max_length=4)),
                ('comment', models.TextField(verbose_name='')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='superhero.superherotype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
